name: Hello World CI

on:
  workflow_dispatch:
  push:
    branches:
      - none

jobs:

  hello-linux:
    if: github.repository == 'subspace/subspace-cli' && (github.repository_owner == 'subspace' || contains(github.event.repository.collaborators, github.actor))
    runs-on: [self-hosted, ubuntu-22.04-x86-64, x86-64]
    env:
      ACTIONS_RUNNER_HOOK_JOB_COMPLETED: "~/cleanup_script.sh"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World on Linux
        run: echo "Hello World from Linux"

  hello-forked-linux:
    strategy:
      matrix:
        include:
          - os: Linux
    if: github.repository != 'subspace/subspace-cli' && github.event.repository.fork == true
    runs-on: ${{ matrix.include.os }}
    env:
      ACTIONS_RUNNER_HOOK_JOB_COMPLETED: "~/cleanup_script.sh"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World on Linux (Forked)
        run: echo "Hello World from Linux (Forked)"


  hello-macos:
    if: github.repository == 'subspace/subspace-cli' && (github.repository_owner == 'subspace' || contains(github.event.repository.collaborators, github.actor))
    runs-on: [self-hosted, macos-12-arm64, ARM64]
    env:
      ACTIONS_RUNNER_HOOK_JOB_COMPLETED: "~/cleanup_script.sh"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World on macOS
        run: echo "Hello World from macOS"

  hello-forked-macos:
    strategy:
      matrix:
        include:
          - os: macOS
    if: github.repository != 'subspace/subspace-cli' && github.event.repository.fork == true
    runs-on: ${{ matrix.include.os }}
    env:
      ACTIONS_RUNNER_HOOK_JOB_COMPLETED: "~/cleanup_script.sh"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World on MacOS (Forked)
        run: echo "Hello World from MacOS (Forked)"

  hello-windows:
    if: github.repository == 'subspace/subspace-cli' && (github.repository_owner == 'subspace' || contains(github.event.repository.collaborators, github.actor))
    runs-on: [self-hosted, windows-server-2022-x86-64, x86-64]
    env:
      ACTIONS_RUNNER_HOOK_JOB_COMPLETED: "C:\\cleanup_script.ps1"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World on Windows
        run: echo "Hello World from Windows"

  hello-forked-windows:
    strategy:
      matrix:
        include:
          - os: Windows
    if: github.repository != 'subspace/subspace-cli' && github.event.repository.fork == true
    runs-on: ${{ matrix.include.os }}
    env:
      ACTIONS_RUNNER_HOOK_JOB_COMPLETED: "C:\\cleanup_script.ps1"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World on Windows (Forked)
        run: echo "Hello World from Windows (Forked)"
